Update to maven-shade-plugin 2.1 to fix CNFE with Maven 3.1+
https://stackoverflow.com/questions/19187811/jenkins-fails-due-to-noclassdeffounderror-org-sonatype-aether-version-versionco
https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound